"""
render_2a_rhf.py — RHF/STO-3G MD Animation for H₂O
=====================================================
Loads pre-computed trajectory from md_data.npz (generated by compute_2a_rhf.py)
and renders the animation.  Compute and render are fully decoupled:

    python part2/compute_2a_rhf.py    # ~2 min  — compute once
    python part2/render_2a_rhf.py     # ~30 s   — render / re-render freely

Layout (2 rows × 3 cols):
  top-left    → Velocity Verlet flowchart  (abstract, engine-agnostic)
  bottom-left → 3-D molecule
  top-mid     → SCF convergence curve
  top-right   → Electron density (YZ plane)
  bottom-mid  → O-H / H-H bond lengths vs. time
  bottom-right→ Energy vs. time  (KE / PE / ΔE_ref on twin axis)

Output: part2a_rhf_md.mp4
"""

import sys
import os
sys.path.insert(0, os.path.dirname(__file__))

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.patches as mpatches
from matplotlib.animation import FuncAnimation, FFMpegWriter
from mpl_toolkits.mplot3d import Axes3D          # noqa: F401
import warnings
warnings.filterwarnings("ignore")

# ---------------------------------------------------------------------------
# Global typography — Arial for all text, Consolas only for the status bar
# ---------------------------------------------------------------------------
matplotlib.rcParams.update({
    "font.family":       "Arial",
    "axes.titlesize":    12,
    "axes.labelsize":    11,
    "xtick.labelsize":   10,
    "ytick.labelsize":   10,
    "legend.fontsize":   9,
})

# ---------------------------------------------------------------------------
# Imports from engine modules (needed only for constants)
# ---------------------------------------------------------------------------
from engine_rhf import HARTREE_TO_EV
from engine_pes  import R0_OH, THETA0

# ---------------------------------------------------------------------------
# Visual constants
# ---------------------------------------------------------------------------
ATOM_SYMBOLS = ["O", "H", "H"]
ATOM_COLORS  = ["#E53935", "#1565C0", "#1565C0"]
ATOM_RADII   = [220, 100, 100]

# ---------------------------------------------------------------------------
# MD / animation parameters  (must match compute_2a_rhf.py)
# ---------------------------------------------------------------------------
N_MD_STEPS      = 20
N_SCF_ITER_SHOW = 4
SCF_CONV_TOL    = 1e-6
DT_FS           = 1.0

FPS_A          = 6
N_SLOW_LOOPS_A = 2
PAUSE_SEC_A    = 1.0

FRAMES_PER_STEP = N_SCF_ITER_SHOW + 3
KEY_SUBS_A      = {N_SCF_ITER_SHOW, N_SCF_ITER_SHOW + 1, N_SCF_ITER_SHOW + 2}

NPZ_PATH = os.path.join(os.path.dirname(__file__), "md_data.npz")

# ---------------------------------------------------------------------------
# Abstract Velocity Verlet flowchart nodes  (engine-agnostic)
# ---------------------------------------------------------------------------
VV_NODES = [
    ("Initialize",              "#607D8B"),   # 0
    ("Compute\nForces",         "#E53935"),   # 1
    ("Update Velocities\n½-kick", "#2E7D32"), # 2
    ("Update\nPositions",       "#1565C0"),   # 3
    ("Update Velocities\n½-kick", "#2E7D32"), # 4
]

# sub-frame → active VV node
def _sub_to_node(step_idx, sub_frame):
    if step_idx == 0 and sub_frame == 0:
        return 0
    if sub_frame <= N_SCF_ITER_SHOW:
        return 1
    if sub_frame == N_SCF_ITER_SHOW + 1:
        return 2
    return 3


# ===========================================================================
# Data loader
# ===========================================================================

def load_md_data(path=NPZ_PATH):
    """Load md_data list-of-dicts from a .npz file saved by compute_2a_rhf.py."""
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"{path} not found.\n"
            "Run:  python part2/compute_2a_rhf.py"
        )
    z = np.load(path)
    n = len(z["step"])
    md_data = []
    for i in range(n):
        md_data.append({
            "step":         int(z["step"][i]),
            "time_fs":      float(z["time_fs"][i]),
            "positions":    z["positions"][i],
            "velocities":   z["velocities"][i],
            "forces":       z["forces"][i],
            "scf_energies": list(z["scf_energies"][i]),
            "density_grid": (z["density_Y"][i], z["density_Z"][i],
                             z["density_rho"][i]),
            "density_hist": list(z["density_hist"][i]),
            "KE":           float(z["KE"][i]),
            "PE_ev":        float(z["PE_ev"][i]),
            "PE_ref_ev":    float(z["PE_ref_ev"][i]),
            "r1":           float(z["r1"][i]),
            "r2":           float(z["r2"][i]),
            "r_HH":         float(z["r_HH"][i]),
            "theta_deg":    float(z["theta_deg"][i]),
        })
    print(f"Loaded {n} MD steps from {path}")
    return md_data


# ===========================================================================
# Animation class
# ===========================================================================

class RHFMDAnimation:
    def __init__(self, md_data):
        self.md_data = md_data
        self.n_steps = len(md_data)

        # Frame schedule
        pause_frames = max(1, int(round(FPS_A * PAUSE_SEC_A)))
        schedule = []
        for step in range(self.n_steps):
            for sub in range(FRAMES_PER_STEP):
                reps = (pause_frames
                        if (step < N_SLOW_LOOPS_A and sub in KEY_SUBS_A)
                        else 1)
                schedule.extend([(step, sub)] * reps)
        self.frame_schedule = schedule
        self.total_frames   = len(schedule)

        # Figure — no suptitle
        self.fig = plt.figure(figsize=(16, 9), facecolor="white")
        self.fig.patch.set_facecolor("white")

        gs = gridspec.GridSpec(
            2, 3, figure=self.fig,
            width_ratios=[1.1, 1.3, 1.3],
            hspace=0.50, wspace=0.40,
            left=0.05, right=0.97, top=0.93, bottom=0.07
        )

        self.ax_flow   = self.fig.add_subplot(gs[0, 0])
        self.ax_mol    = self.fig.add_subplot(gs[1, 0], projection="3d")
        self.ax_scf    = self.fig.add_subplot(gs[0, 1])
        self.ax_den    = self.fig.add_subplot(gs[0, 2])
        self.ax_traj   = self.fig.add_subplot(gs[1, 1])
        self.ax_energy = self.fig.add_subplot(gs[1, 2])

        for ax in [self.ax_flow, self.ax_scf, self.ax_den,
                   self.ax_traj, self.ax_energy]:
            ax.set_facecolor("white")

        # Pre-compute time series
        self.times      = [d["time_fs"]   for d in md_data]
        self.KE_arr     = [d["KE"]        for d in md_data]
        self.PE_arr     = [d["PE_ev"]     for d in md_data]
        self.PE_ref_arr = [d["PE_ref_ev"] for d in md_data]
        self.TE_arr     = [d["KE"] + d["PE_ev"] for d in md_data]
        self.oh1        = [d["r1"]        for d in md_data]
        self.oh2        = [d["r2"]        for d in md_data]
        self.hh         = [d["r_HH"]      for d in md_data]
        self.theta      = [d["theta_deg"] for d in md_data]

        # Density color scale — 95th percentile to avoid core-peak washout
        rho_all = np.concatenate([d["density_grid"][2].ravel() for d in md_data])
        self._rho_max    = float(np.percentile(rho_all, 95))
        self._rho_levels = np.linspace(0, self._rho_max, 22)

        # Fixed-width status text object (Consolas, top centre)
        self._status_txt = self.fig.text(
            0.5, 0.965, "",
            ha="center", va="top",
            fontsize=12, color="#333333",
            fontfamily="Consolas",
        )

    # -----------------------------------------------------------------------
    # Flowchart
    # -----------------------------------------------------------------------
    def _draw_flowchart(self, ax, active_node):
        ax.cla()
        ax.set_facecolor("white")
        ax.set_xlim(0, 1); ax.set_ylim(0, 1); ax.axis("off")
        ax.set_title("Velocity Verlet", fontsize=11,
                     color="#1565C0", fontweight="bold", pad=3)

        n = len(VV_NODES)
        ys = np.linspace(0.90, 0.08, n)
        xc = 0.50
        bw, bh = 0.82, 0.12

        for i, (label, base_col) in enumerate(VV_NODES):
            y = ys[i]
            active = (i == active_node)
            face  = "#FFEB3B" if active else base_col
            edge  = "#F57F17" if active else base_col
            lw    = 2.5 if active else 1.0
            alpha = 1.0 if active else 0.20

            rect = mpatches.FancyBboxPatch(
                (xc - bw / 2, y - bh / 2), bw, bh,
                boxstyle="round,pad=0.01",
                facecolor=face, edgecolor=edge,
                linewidth=lw, alpha=alpha,
                transform=ax.transAxes, clip_on=False
            )
            ax.add_patch(rect)
            ax.text(xc, y, label,
                    ha="center", va="center", fontsize=9,
                    color="#1A1A1A" if active else "white",
                    fontweight="bold" if active else "normal",
                    alpha=1.0 if active else 0.85,
                    transform=ax.transAxes)

            if i < n - 1:
                ax.annotate(
                    "", xy=(xc, ys[i+1] + bh/2 + 0.005),
                    xytext=(xc, y - bh/2 - 0.005),
                    xycoords="axes fraction", textcoords="axes fraction",
                    arrowprops=dict(arrowstyle="-|>", color="#888888",
                                   lw=1.0, mutation_scale=8)
                )

        # Loop-back arrow (nodes 1 → 4)
        ax.annotate(
            "", xy=(xc - bw/2 - 0.02, ys[1]),
            xytext=(xc - bw/2 - 0.02, ys[-1]),
            xycoords="axes fraction", textcoords="axes fraction",
            arrowprops=dict(arrowstyle="-|>", color="#888888",
                            lw=1.0, mutation_scale=8)
        )
        ax.text(0.02, (ys[1] + ys[-1]) / 2, "loop",
                ha="center", va="center", fontsize=9,
                color="#888888", rotation=90, transform=ax.transAxes)

    # -----------------------------------------------------------------------
    # 3-D molecule
    # -----------------------------------------------------------------------
    def _draw_molecule_3d(self, ax, positions, forces=None,
                          velocities=None, disp_from=None, title=""):
        ax.cla(); ax.set_facecolor("white")
        ax.view_init(elev=25, azim=45)

        for i in range(1, 3):
            ax.plot([positions[0,0], positions[i,0]],
                    [positions[0,1], positions[i,1]],
                    [positions[0,2], positions[i,2]],
                    color="#888888", linewidth=2.5, zorder=1)

        for i, (sym, col, sz) in enumerate(zip(ATOM_SYMBOLS, ATOM_COLORS, ATOM_RADII)):
            ax.scatter(positions[i,0], positions[i,1], positions[i,2],
                       s=sz, c=col, edgecolors="white", linewidths=1.5,
                       zorder=5, depthshade=True)
            ax.text(positions[i,0]+0.06, positions[i,1]+0.06, positions[i,2]+0.10,
                    sym, fontsize=11, color=col, fontweight="bold")

        def _quiver(arr, color):
            mx = np.abs(arr).max() + 1e-10
            sc = 0.35 / mx
            for i in range(3):
                v = arr[i] * sc
                if np.linalg.norm(v) > 0.01:
                    ax.quiver(positions[i,0], positions[i,1], positions[i,2],
                              v[0], v[1], v[2], color=color,
                              arrow_length_ratio=0.35, linewidth=1.5, zorder=10)

        if forces    is not None: _quiver(forces,    "#E65100")
        if velocities is not None: _quiver(velocities, "#2E7D32")
        if disp_from is not None:
            disp = positions - disp_from
            _quiver(disp, "#1565C0")

        ax.set_xlim(-1.2, 1.2); ax.set_ylim(-1.2, 1.2); ax.set_zlim(-1.2, 1.2)
        ax.set_xlabel("x (Å)", fontsize=10, labelpad=1)
        ax.set_ylabel("y (Å)", fontsize=10, labelpad=1)
        ax.set_zlabel("z (Å)", fontsize=10, labelpad=1)
        ax.tick_params(labelsize=9)
        ax.xaxis.pane.fill = False
        ax.yaxis.pane.fill = False
        ax.zaxis.pane.fill = False
        ax.grid(True, alpha=0.15)
        ax.set_title(title, fontsize=11, color="#1565C0", pad=2)

    # -----------------------------------------------------------------------
    # SCF convergence
    # -----------------------------------------------------------------------
    def _draw_scf(self, ax, e_hist, n_show, step_idx):
        ax.cla(); ax.set_facecolor("white")
        ax.set_title(f"SCF Convergence  (step {step_idx+1})  [RHF/STO-3G]",
                     fontsize=12, color="#1565C0")
        if not e_hist:
            return
        e_ref  = e_hist[-1]
        delta  = [abs(e - e_ref) + 1e-12 for e in e_hist[:n_show]]
        iters  = np.arange(1, len(delta) + 1)
        ax.semilogy(iters, delta, "o-", color="#1565C0", linewidth=2,
                    markersize=5, markerfacecolor="#E53935")
        ax.axhline(SCF_CONV_TOL, color="#1B5E20", linestyle="--", linewidth=1,
                   alpha=0.7, label=f"tol {SCF_CONV_TOL:.0e}")
        ax.set_xlabel("SCF Iteration")
        ax.set_ylabel("|ΔE| (Hartree)")
        ax.set_xlim(0.5, N_SCF_ITER_SHOW + 0.5)
        ax.set_ylim(1e-8, 2.0)
        ax.legend(); ax.grid(True, alpha=0.3)

    # -----------------------------------------------------------------------
    # Electron density
    # -----------------------------------------------------------------------
    def _draw_density(self, ax, X, Z, rho, positions, scf_iter,
                      forces=None, velocities=None, disp_from=None):
        ax.cla()
        ax.set_facecolor("#DEEBF7")
        ax.set_title(f"Electron Density  (SCF iter {scf_iter}/{N_SCF_ITER_SHOW})",
                     fontsize=12, color="#1565C0")

        ax.contourf(X, Z, rho, levels=self._rho_levels,
                    cmap="Blues", alpha=0.90, extend="min")
        ax.contour(X, Z, rho, levels=self._rho_levels[::3],
                   colors="navy", linewidths=0.5, alpha=0.45)

        for i, (sym, col) in enumerate(zip(ATOM_SYMBOLS, ATOM_COLORS)):
            ax.scatter(positions[i,1], positions[i,2],
                       s=60, c=col, edgecolors="white", linewidths=1.5, zorder=5)
            ax.text(positions[i,1]+0.08, positions[i,2]+0.12,
                    sym, fontsize=11, color=col, fontweight="bold")

        def _arrow2d(arr, color):
            mx = np.abs(arr).max() + 1e-10
            sc = 0.25 / mx
            for i in range(3):
                dy = arr[i,1] * sc; dz = arr[i,2] * sc
                if abs(dy) + abs(dz) > 0.005:
                    ax.annotate("",
                                xy=(positions[i,1]+dy, positions[i,2]+dz),
                                xytext=(positions[i,1], positions[i,2]),
                                arrowprops=dict(arrowstyle="-|>", color=color,
                                               lw=1.5, mutation_scale=12))

        if forces    is not None: _arrow2d(forces,    "#E65100")
        if velocities is not None: _arrow2d(velocities, "#2E7D32")
        if disp_from is not None:
            _arrow2d(positions - disp_from, "#1565C0")

        ax.set_xlabel("y (Å)"); ax.set_ylabel("z (Å)")
        ax.set_xlim(-2.0, 2.0); ax.set_ylim(-1.5, 1.5)
        ax.set_aspect("equal")

        legend_items = []
        if forces    is not None:
            legend_items.append(mpatches.Patch(color="#E65100", label="Force F"))
        if velocities is not None:
            legend_items.append(mpatches.Patch(color="#2E7D32", label="Velocity v"))
        if disp_from is not None:
            legend_items.append(mpatches.Patch(color="#1565C0", label="Displacement Δr"))
        if legend_items:
            ax.legend(handles=legend_items, fontsize=9, loc="upper right",
                      framealpha=0.8)

        ax.text(0.5, 0.02, f"SCF iter: {scf_iter}/{N_SCF_ITER_SHOW}",
                ha="center", fontsize=10, color="#1565C0",
                transform=ax.transAxes,
                bbox=dict(boxstyle="round,pad=0.2", facecolor="#E3F2FD",
                          edgecolor="#1565C0", alpha=0.8))

    # -----------------------------------------------------------------------
    # Geometry diagnostics
    # -----------------------------------------------------------------------
    def _draw_trajectory(self, ax, up_to):
        ax.cla(); ax.set_facecolor("white")
        t = self.times[:up_to + 1]
        ax.plot(t, self.oh1[:up_to+1], "-o", color="#1565C0",
                linewidth=2, markersize=3, label="O–H₁")
        ax.plot(t, self.oh2[:up_to+1], "-s", color="#E53935",
                linewidth=2, markersize=3, label="O–H₂")
        ax.plot(t, self.hh[:up_to+1],  "-^", color="#6A1B9A",
                linewidth=2, markersize=3, label="H–H")
        ax.axhline(R0_OH, color="#1B5E20", linestyle="--", linewidth=1,
                   alpha=0.7, label=f"eq. O–H {R0_OH:.4f} Å")
        hh_eq = 2.0 * R0_OH * np.sin(THETA0 / 2.0)
        ax.axhline(hh_eq, color="#6A1B9A", linestyle=":",
                   linewidth=1.2, alpha=0.8, label=f"eq. H–H {hh_eq:.3f} Å")
        ax.set_xlabel("Time (fs)"); ax.set_ylabel("Distance (Å)")
        ax.set_title("Geometry Diagnostics (O–H / H–H)", fontsize=12, color="#1565C0")
        ax.set_xlim(-0.2, self.times[-1] + 0.2)
        all_r = self.oh1[:up_to+1] + self.oh2[:up_to+1] + self.hh[:up_to+1]
        r_min, r_max = min(all_r), max(all_r)
        r_pad = max(0.08, 0.15 * (r_max - r_min + 1e-12))
        ax.set_ylim(r_min - r_pad, r_max + r_pad)
        ax.legend(fontsize=9); ax.grid(True, alpha=0.3)
        ax.text(0.02, 0.05, f"θ(HOH) = {self.theta[up_to]:.2f}°",
                transform=ax.transAxes, fontsize=10, color="#6A1B9A",
                bbox=dict(boxstyle="round,pad=0.2", facecolor="#F3E5F5",
                          edgecolor="#6A1B9A", alpha=0.8))

    # -----------------------------------------------------------------------
    # Energy
    # -----------------------------------------------------------------------
    def _draw_energy(self, ax, up_to):
        ax.cla(); ax.set_facecolor("white")
        t = self.times[:up_to + 1]

        ax.plot(t, self.KE_arr[:up_to+1], "-", color="#E65100",
                linewidth=2, label="KE")
        ax.plot(t, self.PE_arr[:up_to+1], "-", color="#1565C0",
                linewidth=2, label="PE (PES)")
        ax.plot(t, self.TE_arr[:up_to+1], "-", color="#1B5E20",
                linewidth=2.5, label="Total (KE+PES)")
        ax.set_xlabel("Time (fs)"); ax.set_ylabel("Energy (eV)")
        ax.set_title("Energy vs. Time", fontsize=12, color="#1565C0")
        ax.set_xlim(-0.2, self.times[-1] + 0.2)
        ax.grid(True, alpha=0.3)

        ax2 = ax.twinx()
        e_ref_rel = [e - self.PE_ref_arr[0] for e in self.PE_ref_arr[:up_to+1]]
        ax2.plot(t, e_ref_rel, "--", color="#8E24AA",
                 linewidth=1.8, label="ΔE_ref (SCF)")
        ax2.set_ylabel("ΔE_ref (eV)", fontsize=10, color="#8E24AA")
        ax2.tick_params(axis="y", labelcolor="#8E24AA", labelsize=9)

        lines1, labels1 = ax.get_legend_handles_labels()
        lines2, labels2 = ax2.get_legend_handles_labels()
        ax.legend(lines1 + lines2, labels1 + labels2, fontsize=9, loc="upper right")

        if up_to > 3:
            te_std  = np.std(self.TE_arr[:up_to+1])
            te_mean = np.mean(self.TE_arr[:up_to+1])
            ax.text(0.02, 0.05,
                    f"ΔE/E = {te_std / (abs(te_mean) + 1e-12) * 100:.3f}%",
                    transform=ax.transAxes, fontsize=10, color="#555555")

    # -----------------------------------------------------------------------
    # Main animate
    # -----------------------------------------------------------------------
    def animate(self, frame_idx):
        step_idx, sub_frame = self.frame_schedule[frame_idx]
        d = self.md_data[step_idx]

        active_node = _sub_to_node(step_idx, sub_frame)

        if step_idx == 0 and sub_frame == 0:
            scf_show = 1
            rho_show = d["density_hist"][0]
        elif sub_frame < N_SCF_ITER_SHOW:
            scf_show = sub_frame + 1
            rho_show = d["density_hist"][sub_frame]
        else:
            scf_show = N_SCF_ITER_SHOW
            rho_show = d["density_grid"][2]

        show_forces = (sub_frame == N_SCF_ITER_SHOW)
        show_vel    = (sub_frame == N_SCF_ITER_SHOW + 1)
        show_disp   = (sub_frame == N_SCF_ITER_SHOW + 2)
        prev_pos    = (self.md_data[step_idx-1]["positions"]
                       if step_idx > 0 else d["positions"])
        X, Z, _     = d["density_grid"]

        self._draw_flowchart(self.ax_flow, active_node)
        self._draw_molecule_3d(
            self.ax_mol, d["positions"],
            forces     = d["forces"]     if show_forces else None,
            velocities = d["velocities"] if show_vel    else None,
            disp_from  = prev_pos        if show_disp   else None,
            title=f"H₂O  (step {step_idx+1})"
        )
        self._draw_scf(self.ax_scf, d["scf_energies"], scf_show, step_idx)
        self._draw_density(
            self.ax_den, X, Z, rho_show, d["positions"], scf_show,
            forces     = d["forces"]     if show_forces else None,
            velocities = d["velocities"] if show_vel    else None,
            disp_from  = prev_pos        if show_disp   else None,
        )
        self._draw_trajectory(self.ax_traj, step_idx)
        self._draw_energy(self.ax_energy, step_idx)

        phases = {
            0: "Initializing          ",
            1: "Computing forces      ",
            2: "Velocity half-kick    ",
            3: "Updating positions    ",
        }
        phase_str = phases.get(active_node, "                      ")
        status = (f"Step {step_idx+1:02d}/{self.n_steps:02d}"
                  f"  |  t = {d['time_fs']:5.1f} fs"
                  f"  |  {phase_str}")
        self._status_txt.set_text(status)

        return []

    def run(self, output="part2a_rhf_md.mp4", fps=FPS_A):
        print(f"\nRendering {self.total_frames} frames @ {fps} fps -> {output}")
        print(f"  Duration: {self.total_frames / fps:.1f}s")
        ani = FuncAnimation(self.fig, self.animate,
                            frames=self.total_frames,
                            interval=1000 // fps, blit=False)
        writer = FFMpegWriter(fps=fps, bitrate=2000,
                              metadata={"title": "H2O RHF/STO-3G MD"})
        ani.save(output, writer=writer, dpi=130)
        print(f"Saved: {output}")
        plt.close(self.fig)


# ===========================================================================
if __name__ == "__main__":
    md_data = load_md_data()
    anim = RHFMDAnimation(md_data)
    anim.run(output="part2a_rhf_md.mp4", fps=FPS_A)
