"""
render_2c_deepmd.py — DeePMD-kit MD Animation for H₂O
=======================================================
Loads pre-computed trajectory from deepmd_data.npz (generated by
compute_2c_deepmd.py) and renders the animation.
Compute and render are fully decoupled:

    python part2/compute_2c_deepmd.py   # Bohrium run
    python part2/render_2c_deepmd.py    # render / re-render freely

Layout (2 rows × 3 cols, 16×9):
  top-left     → Abstract Velocity Verlet flowchart
  bottom-left  → 3-D molecule with cutoff sphere around focused atom
  top-mid      → Descriptor pipeline: s_ij bar chart + cutoff curve
  top-right    → Per-atom energy accumulation: ε_i stacking → E_total
  bottom-mid   → Gradient → Force: force magnitude bars per atom
  bottom-right → MD monitoring (KE / PE / TE + O-H bond lengths)

Output: part2c_deepmd.mp4
"""

import os
import sys
import argparse
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.patches as mpatches
from matplotlib.animation import FuncAnimation, FFMpegWriter
from mpl_toolkits.mplot3d import Axes3D   # noqa: F401
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
import warnings
warnings.filterwarnings("ignore")

# ---------------------------------------------------------------------------
# Global typography
# ---------------------------------------------------------------------------
matplotlib.rcParams.update({
    "font.family":    "Arial",
    "axes.titlesize": 11,
    "axes.labelsize": 10,
    "xtick.labelsize": 9,
    "ytick.labelsize": 9,
    "legend.fontsize": 8,
})

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
HERE     = os.path.dirname(os.path.abspath(__file__))
NPZ_PATH = os.path.join(HERE, "deepmd_data.npz")

# ---------------------------------------------------------------------------
# Visual constants
# ---------------------------------------------------------------------------
ATOM_SYMBOLS = ["O", "H", "H"]
ATOM_COLORS  = ["#E53935", "#1565C0", "#1565C0"]
ATOM_SIZES   = [300, 150, 150]

R_CUT   = 6.0    # Å — cutoff used in worker
R_INNER = 0.5

# Animation parameters
FPS_C          = 8
N_SUB_FRAMES   = 4   # sub-frames per MD step
N_SLOW_LOOPS_C = 2
PAUSE_SEC_C    = 0.8

# ---------------------------------------------------------------------------
# Abstract Velocity Verlet flowchart nodes
# ---------------------------------------------------------------------------
VV_NODES = [
    ("Initialize",               "#607D8B"),   # 0
    ("Compute\nForces",          "#E53935"),   # 1
    ("Update Velocities\n½-kick","#2E7D32"),   # 2
    ("Update\nPositions",        "#1565C0"),   # 3
    ("Update Velocities\n½-kick","#2E7D32"),   # 4
]

def _sub_to_node(step_idx, sub_frame):
    if step_idx == 0 and sub_frame == 0:
        return 0
    if sub_frame == 0:
        return 1
    if sub_frame == 1:
        return 2
    if sub_frame == 2:
        return 3
    return 4


# ---------------------------------------------------------------------------
# Smooth cutoff (for descriptor inset visualization only)
# ---------------------------------------------------------------------------
def _f_cut(r_arr, r_cut=R_CUT, r_inner=R_INNER):
    r = np.asarray(r_arr, dtype=float)
    out = np.zeros_like(r)
    m_in  = r < r_inner
    m_mid = (r >= r_inner) & (r < r_cut)
    out[m_in] = 1.0
    u = (r[m_mid] - r_inner) / (r_cut - r_inner)
    out[m_mid] = u**3 * (-6*u**2 + 15*u - 10) + 1.0
    return out


# ---------------------------------------------------------------------------
# Sphere wireframe helper for 3D cutoff domain
# ---------------------------------------------------------------------------
def _sphere_wireframe(cx, cy, cz, r, n=12):
    """Return (xs, ys, zs) lists of line segments for a sphere wireframe."""
    lines = []
    # latitude circles
    for lat in np.linspace(-np.pi/2, np.pi/2, n//2):
        phi = np.linspace(0, 2*np.pi, 40)
        x = cx + r * np.cos(lat) * np.cos(phi)
        y = cy + r * np.cos(lat) * np.sin(phi)
        z = cz + r * np.sin(lat) * np.ones_like(phi)
        lines.append((x, y, z))
    # longitude circles
    for lon in np.linspace(0, np.pi, n//2):
        theta = np.linspace(0, 2*np.pi, 40)
        x = cx + r * np.sin(theta) * np.cos(lon)
        y = cy + r * np.sin(theta) * np.sin(lon)
        z = cz + r * np.cos(theta)
        lines.append((x, y, z))
    return lines


# ===========================================================================
# Data loader
# ===========================================================================

def load_data(path=NPZ_PATH):
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"{path} not found.\n"
            "Run:  python part2/compute_2c_deepmd.py"
        )
    z = np.load(path, allow_pickle=True)
    n = len(z["steps"])

    label = str(z["label"][0]) if "label" in z else "DeePMD-kit"

    traj = []
    for i in range(n):
        traj.append({
            "step":       int(z["steps"][i]),
            "time_fs":    float(z["time_fs"][i]),
            "positions":  z["positions"][i],
            "velocities": z["velocities"][i],
            "forces":     z["forces"][i],
            "E_total":    float(z["E_total"][i]),
            "per_atom_e": z["per_atom_e"][i],
            "KE":         float(z["KE"][i]),
            "TE":         float(z["TE"][i]),
            "r_ij":       z["r_ij"][i],    # (3, 2)
            "s_ij":       z["s_ij"][i],    # (3, 2)
            "n_nbr":      z["n_nbr"][i],   # (3,)
        })

    print(f"Loaded {n} MD steps from {path}  [{label}]")
    return traj, label


# ===========================================================================
# Animation class
# ===========================================================================

class DeePMDAnimation:
    def __init__(self, traj, model_label="DeePMD-kit"):
        self.traj        = traj
        self.n_steps     = len(traj)
        self.model_label = model_label

        # ── Frame schedule ─────────────────────────────────────────────────
        pause_frames = max(1, int(round(FPS_C * PAUSE_SEC_C)))
        KEY_SUBS = {0, 1, 2, 3}
        schedule = []
        for step in range(self.n_steps):
            for sub in range(N_SUB_FRAMES):
                reps = (pause_frames
                        if (step < N_SLOW_LOOPS_C and sub in KEY_SUBS)
                        else 1)
                schedule.extend([(step, sub)] * reps)
        self.frame_schedule = schedule
        self.total_frames   = len(schedule)

        # ── Figure — 2×3, 16×9 ────────────────────────────────────────────
        self.fig = plt.figure(figsize=(16, 9), facecolor="white")
        self.fig.patch.set_facecolor("white")

        gs = gridspec.GridSpec(
            2, 3, figure=self.fig,
            width_ratios=[1.0, 1.3, 1.3],
            hspace=0.48, wspace=0.38,
            left=0.04, right=0.97, top=0.93, bottom=0.07,
        )

        self.ax_flow  = self.fig.add_subplot(gs[0, 0])          # top-left
        self.ax_mol   = self.fig.add_subplot(gs[1, 0],
                                             projection="3d")   # bottom-left
        self.ax_desc  = self.fig.add_subplot(gs[0, 1])          # top-mid
        self.ax_accum = self.fig.add_subplot(gs[0, 2])          # top-right
        self.ax_grad  = self.fig.add_subplot(gs[1, 1])          # bottom-mid
        self.ax_mon   = self.fig.add_subplot(gs[1, 2])          # bottom-right

        for ax in [self.ax_flow, self.ax_desc, self.ax_accum,
                   self.ax_grad, self.ax_mon]:
            ax.set_facecolor("white")

        # ── Pre-compute time series ────────────────────────────────────────
        self.times   = [d["time_fs"]  for d in traj]
        self.KE_arr  = [d["KE"]       for d in traj]
        self.PE_arr  = [d["E_total"]  for d in traj]
        self.TE_arr  = [d["TE"]       for d in traj]
        self.oh1_arr = [float(np.linalg.norm(d["positions"][1] - d["positions"][0]))
                        for d in traj]
        self.oh2_arr = [float(np.linalg.norm(d["positions"][2] - d["positions"][0]))
                        for d in traj]

        # ── Status bar ────────────────────────────────────────────────────
        self._status_txt = self.fig.text(
            0.5, 0.965, "",
            ha="center", va="top",
            fontsize=11, color="#333333",
            fontfamily="Consolas",
        )

    # -----------------------------------------------------------------------
    # Panel A (top-left): Abstract Velocity Verlet flowchart
    # -----------------------------------------------------------------------
    def _draw_flowchart(self, ax, active_node):
        ax.cla()
        ax.set_facecolor("white")
        ax.set_xlim(0, 1); ax.set_ylim(0, 1); ax.axis("off")
        ax.set_title("Velocity Verlet", fontsize=11,
                     color="#1565C0", fontweight="bold", pad=3)

        n  = len(VV_NODES)
        ys = np.linspace(0.90, 0.08, n)
        xc = 0.50
        bw, bh = 0.82, 0.12

        for i, (label, base_col) in enumerate(VV_NODES):
            y      = ys[i]
            active = (i == active_node)
            face   = "#FFEB3B" if active else base_col
            edge   = "#F57F17" if active else base_col
            lw     = 2.5 if active else 1.0
            alpha  = 1.0 if active else 0.20

            rect = mpatches.FancyBboxPatch(
                (xc - bw / 2, y - bh / 2), bw, bh,
                boxstyle="round,pad=0.01",
                facecolor=face, edgecolor=edge,
                linewidth=lw, alpha=alpha,
                transform=ax.transAxes, clip_on=False,
            )
            ax.add_patch(rect)
            ax.text(xc, y, label,
                    ha="center", va="center", fontsize=9,
                    color="#1A1A1A" if active else "white",
                    fontweight="bold" if active else "normal",
                    alpha=1.0 if active else 0.85,
                    transform=ax.transAxes)

            if i < n - 1:
                ax.annotate(
                    "", xy=(xc, ys[i+1] + bh/2 + 0.005),
                    xytext=(xc, y - bh/2 - 0.005),
                    xycoords="axes fraction", textcoords="axes fraction",
                    arrowprops=dict(arrowstyle="-|>", color="#888888",
                                   lw=1.0, mutation_scale=8),
                )

        ax.annotate(
            "", xy=(xc - bw/2 - 0.02, ys[1]),
            xytext=(xc - bw/2 - 0.02, ys[-1]),
            xycoords="axes fraction", textcoords="axes fraction",
            arrowprops=dict(arrowstyle="-|>", color="#888888",
                            lw=1.0, mutation_scale=8),
        )
        ax.text(0.02, (ys[1] + ys[-1]) / 2, "loop",
                ha="center", va="center", fontsize=9,
                color="#888888", rotation=90, transform=ax.transAxes)

    # -----------------------------------------------------------------------
    # Panel B (bottom-left): 3-D molecule + cutoff sphere
    # -----------------------------------------------------------------------
    def _draw_molecule_3d(self, ax, d, focus_atom=0,
                          show_forces=False, show_vel=False,
                          show_disp=False, prev_pos=None):
        ax.cla()
        ax.set_facecolor("white")
        ax.view_init(elev=25, azim=45)

        pos = d["positions"]

        # ── Cutoff sphere around focused atom ─────────────────────────────
        fc = pos[focus_atom]
        sphere_lines = _sphere_wireframe(fc[0], fc[1], fc[2], R_CUT, n=8)
        for (sx, sy, sz) in sphere_lines:
            ax.plot(sx, sy, sz, color=ATOM_COLORS[focus_atom],
                    alpha=0.08, linewidth=0.5, zorder=0)

        # ── Bonds ─────────────────────────────────────────────────────────
        for i in range(1, 3):
            ax.plot([pos[0,0], pos[i,0]],
                    [pos[0,1], pos[i,1]],
                    [pos[0,2], pos[i,2]],
                    color="#888888", linewidth=2.5, zorder=1)

        # ── Atoms ─────────────────────────────────────────────────────────
        for i, (sym, col, sz) in enumerate(zip(ATOM_SYMBOLS, ATOM_COLORS, ATOM_SIZES)):
            edge = "#F57F17" if i == focus_atom else "white"
            lw   = 2.5 if i == focus_atom else 1.5
            ax.scatter(pos[i,0], pos[i,1], pos[i,2],
                       s=sz, c=col, edgecolors=edge,
                       linewidths=lw, zorder=5, depthshade=True)
            ax.text(pos[i,0]+0.06, pos[i,1]+0.06, pos[i,2]+0.10,
                    sym, fontsize=11, color=col, fontweight="bold")

        # ── Neighbor connection lines (within cutoff) ─────────────────────
        n_nbr = int(d["n_nbr"][focus_atom])
        nbr_indices = [j for j in range(3) if j != focus_atom][:n_nbr]
        for j in nbr_indices:
            ax.plot([fc[0], pos[j,0]], [fc[1], pos[j,1]], [fc[2], pos[j,2]],
                    color=ATOM_COLORS[focus_atom], alpha=0.4,
                    linewidth=1.0, linestyle="--", zorder=2)

        def _quiver(arr, color):
            mx = np.abs(arr).max() + 1e-10
            sc = 0.35 / mx
            for i in range(3):
                v = arr[i] * sc
                if np.linalg.norm(v) > 0.01:
                    ax.quiver(pos[i,0], pos[i,1], pos[i,2],
                              v[0], v[1], v[2],
                              color=color, arrow_length_ratio=0.35,
                              linewidth=1.5, zorder=10)

        if show_forces:
            _quiver(d["forces"],    "#E65100")
        if show_vel:
            _quiver(d["velocities"],"#2E7D32")
        if show_disp and prev_pos is not None:
            _quiver(pos - prev_pos, "#1565C0")

        ax.set_xlim(-1.2, 1.2); ax.set_ylim(-1.2, 1.2); ax.set_zlim(-1.2, 1.2)
        ax.set_xlabel("x (Å)", fontsize=9, labelpad=1)
        ax.set_ylabel("y (Å)", fontsize=9, labelpad=1)
        ax.set_zlabel("z (Å)", fontsize=9, labelpad=1)
        ax.tick_params(labelsize=8)
        ax.xaxis.pane.fill = False
        ax.yaxis.pane.fill = False
        ax.zaxis.pane.fill = False
        ax.grid(True, alpha=0.15)
        ax.set_title(
            f"H₂O  (step {d['step']+1})  "
            f"[focus: {ATOM_SYMBOLS[focus_atom]}, r_cut={R_CUT}Å]",
            fontsize=10, color="#1565C0", pad=2,
        )

    # -----------------------------------------------------------------------
    # Panel C (top-mid): Descriptor pipeline — s_ij bars + cutoff curve
    # -----------------------------------------------------------------------
    def _draw_descriptor(self, ax, d, focus_atom=0):
        ax.cla()
        for child in list(ax.child_axes):
            child.remove()
        ax.set_facecolor("white")
        ax.axis("off")
        ax.set_title(
            f"Descriptor  (focus: {ATOM_SYMBOLS[focus_atom]})",
            fontsize=11, color="#E65100", pad=4,
        )

        # ── Main: s_ij bar chart ───────────────────────────────────────────
        ax_sij = ax.inset_axes([0.04, 0.10, 0.58, 0.80])
        ax_sij.set_facecolor("white")

        n_nbr  = int(d["n_nbr"][focus_atom])
        r_vals = d["r_ij"][focus_atom, :n_nbr]
        s_vals = d["s_ij"][focus_atom, :n_nbr]

        if n_nbr > 0:
            nbr_indices = [j for j in range(3) if j != focus_atom][:n_nbr]
            tick_labels = [f"{ATOM_SYMBOLS[j]}\nr={r:.2f}Å"
                           for j, r in zip(nbr_indices, r_vals)]
            bar_colors  = [ATOM_COLORS[j] for j in nbr_indices]
            x_pos = np.arange(n_nbr, dtype=float)
            bars = ax_sij.bar(x_pos, s_vals,
                              color=bar_colors, edgecolor="white",
                              linewidth=1.5, alpha=0.85)
            ax_sij.set_xticks(x_pos)
            ax_sij.set_xticklabels(tick_labels, fontsize=8)
            for bar, s in zip(bars, s_vals):
                ax_sij.text(
                    bar.get_x() + bar.get_width() / 2,
                    bar.get_height() + 0.002,
                    f"{s:.3f}",
                    ha="center", va="bottom", fontsize=9, color="#333333",
                )
        else:
            ax_sij.text(0.5, 0.5, "No neighbors\nin cutoff",
                        ha="center", va="center",
                        transform=ax_sij.transAxes, fontsize=10)

        ax_sij.set_ylabel(r"$s_{ij}=f_{\rm cut}(r)/r$  ($\AA^{-1}$)", fontsize=9)
        ax_sij.set_title(
            f"s_ij  (descriptor of {ATOM_SYMBOLS[focus_atom]})",
            fontsize=9, color="#E65100",
        )
        ax_sij.tick_params(labelsize=8)
        ax_sij.grid(True, alpha=0.3, axis="y")

        # ── Inset: cutoff function curve ───────────────────────────────────
        ax_fc = ax.inset_axes([0.66, 0.52, 0.32, 0.40])
        r_arr = np.linspace(0, R_CUT + 0.5, 200)
        ax_fc.plot(r_arr, _f_cut(r_arr), color="#E65100", linewidth=1.5)
        ax_fc.axvline(R_CUT,   color="#888888", linestyle="--", linewidth=1)
        ax_fc.axvline(R_INNER, color="#AAAAAA", linestyle=":",  linewidth=1)
        if n_nbr > 0:
            for r in r_vals:
                ax_fc.axvline(r, color="#1565C0", linestyle="-",
                              linewidth=1.2, alpha=0.7)
        ax_fc.set_xlabel("r (Å)", fontsize=6)
        ax_fc.set_ylabel("f_cut(r)", fontsize=6)
        ax_fc.set_title(f"Cutoff  r_c={R_CUT}Å", fontsize=6)
        ax_fc.tick_params(labelsize=5)
        ax_fc.set_facecolor("#F8F9FA")
        ax_fc.set_xlim(0, R_CUT + 0.5)
        ax_fc.set_ylim(-0.05, 1.15)

        # ── Arrow + label: embed + fit ─────────────────────────────────────
        ax.annotate(
            "embed\n+ fit\n→ ε_i",
            xy=(0.66, 0.50), xytext=(0.64, 0.50),
            xycoords="axes fraction", textcoords="axes fraction",
            fontsize=8, color="#555555", ha="right", va="center",
        )

    # -----------------------------------------------------------------------
    # Panel D (top-right): Per-atom energy accumulation → E_total
    # -----------------------------------------------------------------------
    def _draw_accumulation(self, ax, d):
        ax.cla()
        ax.set_facecolor("white")

        per_e   = d["per_atom_e"]          # (3,) eV
        E_total = d["E_total"]             # eV

        # Stacked horizontal bar: ε_O | ε_H1 | ε_H2 → E_total
        # Show absolute values as stacked segments, with sign indicated
        # Use a waterfall / cumulative bar approach
        x_pos = np.arange(4, dtype=float)   # O, H1, H2, Σ
        labels = ["ε_O", "ε_H₁", "ε_H₂", "E_total\n= Σ ε_i"]
        colors = ATOM_COLORS + ["#1B5E20"]

        # Cumulative sum for waterfall
        cumsum = np.concatenate([[0], np.cumsum(per_e)])
        bar_bottoms = cumsum[:3]
        bar_heights = per_e

        bars = ax.bar(x_pos[:3], bar_heights, bottom=bar_bottoms,
                      color=ATOM_COLORS, edgecolor="white",
                      linewidth=1.5, alpha=0.85, width=0.6)

        # E_total bar (full height from 0)
        ax.bar(3, E_total, bottom=0,
               color="#1B5E20", edgecolor="white",
               linewidth=1.5, alpha=0.85, width=0.6)

        # Connector lines showing accumulation
        for i in range(3):
            top = float(cumsum[i+1])
            ax.plot([i + 0.3, i + 0.7 + 0.3], [top, top],
                    color="#888888", linewidth=0.8, linestyle="--", alpha=0.6)

        # Value labels
        for i, (e, bot) in enumerate(zip(per_e, bar_bottoms)):
            mid = float(bot) + float(e) / 2
            ax.text(i, mid, f"{e:.4f}",
                    ha="center", va="center", fontsize=8,
                    color="white", fontweight="bold")
        ax.text(3, E_total / 2, f"{E_total:.4f}",
                ha="center", va="center", fontsize=8,
                color="white", fontweight="bold")

        ax.set_xticks(x_pos)
        ax.set_xticklabels(labels, fontsize=9)
        ax.set_ylabel("Energy (eV)", fontsize=9)
        ax.set_title(
            f"Per-atom ε_i  →  E = Σ ε_i = {E_total:.4f} eV",
            fontsize=10, color="#1B5E20", pad=4,
        )
        ax.axhline(0, color="#888888", linewidth=0.8)
        ax.grid(True, alpha=0.25, axis="y")
        ax.tick_params(labelsize=8)

        # Sigma arrow
        ax.annotate(
            "", xy=(3 - 0.35, E_total * 0.95),
            xytext=(2 + 0.35, float(cumsum[3]) * 0.95),
            arrowprops=dict(arrowstyle="-|>", color="#1B5E20",
                            lw=1.2, mutation_scale=10),
        )

    # -----------------------------------------------------------------------
    # Panel E (bottom-mid): Gradient → Force
    # -----------------------------------------------------------------------
    def _draw_gradient_force(self, ax, d):
        ax.cla()
        ax.set_facecolor("white")

        forces  = d["forces"]    # (3, 3) eV/Å
        f_norms = np.linalg.norm(forces, axis=1)   # (3,) eV/Å

        x_pos  = np.arange(3, dtype=float)
        labels = [f"{sym}\n|F|={fn:.3f}" for sym, fn in zip(ATOM_SYMBOLS, f_norms)]

        bars = ax.bar(x_pos, f_norms,
                      color=ATOM_COLORS, edgecolor="white",
                      linewidth=1.5, alpha=0.85, width=0.5)

        for bar, fn in zip(bars, f_norms):
            ax.text(
                bar.get_x() + bar.get_width() / 2,
                bar.get_height() + 0.002,
                f"{fn:.3f}",
                ha="center", va="bottom", fontsize=9, color="#333333",
            )

        ax.set_xticks(x_pos)
        ax.set_xticklabels(labels, fontsize=9)
        ax.set_ylabel(r"|F$_i$|  (eV/$\AA$)", fontsize=9)
        ax.set_title(
            r"$\mathbf{F}_i = -\nabla_i E$  (force magnitude per atom)",
            fontsize=10, color="#E53935", pad=4,
        )
        ax.grid(True, alpha=0.25, axis="y")
        ax.tick_params(labelsize=8)

        # Component breakdown inset
        ax_comp = ax.inset_axes([0.62, 0.38, 0.36, 0.56])
        ax_comp.set_facecolor("#F8F9FA")
        comp_labels = ["Fx", "Fy", "Fz"]
        comp_colors = ["#E53935", "#1565C0", "#2E7D32"]
        x_c = np.arange(3, dtype=float)
        for atom_i, (sym, col) in enumerate(zip(ATOM_SYMBOLS, ATOM_COLORS)):
            f_xyz = forces[atom_i]
            ax_comp.bar(x_c + atom_i * 0.25 - 0.25, f_xyz,
                        width=0.22, color=comp_colors,
                        alpha=0.7, label=sym if atom_i == 0 else "")
        ax_comp.axhline(0, color="#888888", linewidth=0.6)
        ax_comp.set_xticks(x_c)
        ax_comp.set_xticklabels(comp_labels, fontsize=6)
        ax_comp.set_ylabel(r"eV/$\AA$", fontsize=6)
        ax_comp.set_title("F components", fontsize=6)
        ax_comp.tick_params(labelsize=5)

    # -----------------------------------------------------------------------
    # Panel F (bottom-right): MD monitoring
    # -----------------------------------------------------------------------
    def _draw_monitoring(self, ax, step_idx):
        ax.cla()
        for child in list(ax.child_axes):
            child.remove()
        ax.set_facecolor("white")
        ax.axis("off")
        ax.set_title("MD Monitoring", fontsize=11, color="#1565C0", pad=4)

        up_to = step_idx + 1
        t     = self.times[:up_to]

        ax_e = ax.inset_axes([0.06, 0.52, 0.88, 0.44])
        ax_e.set_facecolor("white")
        ax_e.plot(t, self.KE_arr[:up_to], "-",  color="#E65100",
                  linewidth=2, label="KE")
        ax_e.plot(t, self.PE_arr[:up_to], "-",  color="#1565C0",
                  linewidth=2, label="PE (DeePMD)")
        ax_e.plot(t, self.TE_arr[:up_to], "-",  color="#1B5E20",
                  linewidth=2.5, label="Total E")
        ax_e.set_xlabel("Time (fs)", fontsize=9)
        ax_e.set_ylabel("Energy (eV)", fontsize=9)
        ax_e.set_xlim(-0.2, self.times[-1] + 0.2)
        ax_e.legend(fontsize=7, loc="upper right")
        ax_e.grid(True, alpha=0.3)
        ax_e.tick_params(labelsize=8)
        ax_e.set_title("Energy vs. Time", fontsize=9, color="#1565C0")

        if up_to > 3:
            te_std  = np.std(self.TE_arr[:up_to])
            te_mean = np.mean(self.TE_arr[:up_to])
            ax_e.text(0.02, 0.05,
                      f"ΔE/E = {te_std / (abs(te_mean) + 1e-12) * 100:.3f}%",
                      transform=ax_e.transAxes, fontsize=8, color="#555555")

        ax_r = ax.inset_axes([0.06, 0.04, 0.88, 0.42])
        ax_r.set_facecolor("white")
        ax_r.plot(t, self.oh1_arr[:up_to], "-o", color="#1565C0",
                  linewidth=2, markersize=3, label="O–H₁")
        ax_r.plot(t, self.oh2_arr[:up_to], "-s", color="#E53935",
                  linewidth=2, markersize=3, label="O–H₂")
        ax_r.axhline(0.9572, color="#1B5E20", linestyle="--",
                     linewidth=1, alpha=0.7, label="eq. 0.957 Å")
        ax_r.set_xlabel("Time (fs)", fontsize=9)
        ax_r.set_ylabel("Distance (Å)", fontsize=9)
        ax_r.set_xlim(-0.2, self.times[-1] + 0.2)
        ax_r.legend(fontsize=7, loc="upper right")
        ax_r.grid(True, alpha=0.3)
        ax_r.tick_params(labelsize=8)
        ax_r.set_title("O–H Bond Lengths", fontsize=9, color="#1565C0")

    # -----------------------------------------------------------------------
    # Main animate callback
    # -----------------------------------------------------------------------
    def animate(self, frame_idx):
        step_idx, sub_frame = self.frame_schedule[frame_idx]
        d = self.traj[step_idx]

        active_node = _sub_to_node(step_idx, sub_frame)

        show_forces = (sub_frame == 0)
        show_vel    = (sub_frame == 1)
        show_disp   = (sub_frame == 2)
        prev_pos    = (self.traj[step_idx - 1]["positions"]
                       if step_idx > 0 else d["positions"])

        focus_atom = step_idx % 3

        self._draw_flowchart(self.ax_flow, active_node)
        self._draw_molecule_3d(
            self.ax_mol, d,
            focus_atom  = focus_atom,
            show_forces = show_forces,
            show_vel    = show_vel,
            show_disp   = show_disp,
            prev_pos    = prev_pos,
        )
        self._draw_descriptor(self.ax_desc, d, focus_atom)
        self._draw_accumulation(self.ax_accum, d)
        self._draw_gradient_force(self.ax_grad, d)
        self._draw_monitoring(self.ax_mon, step_idx)

        phases = {
            0: "Initializing          ",
            1: "Computing forces      ",
            2: "Velocity half-kick    ",
            3: "Updating positions    ",
            4: "Velocity half-kick    ",
        }
        phase_str = phases.get(active_node, "                      ")
        status = (
            f"Step {step_idx+1:02d}/{self.n_steps:02d}"
            f"  |  t = {d['time_fs']:5.1f} fs"
            f"  |  {phase_str}"
            f"  |  {self.model_label}"
        )
        self._status_txt.set_text(status)

        return []

    # -----------------------------------------------------------------------
    def run(self, output="part2c_deepmd.mp4", fps=FPS_C):
        print(f"\nRendering {self.total_frames} frames @ {fps} fps → {output}")
        print(f"  Duration: {self.total_frames / fps:.1f} s")
        ani = FuncAnimation(
            self.fig, self.animate,
            frames=self.total_frames,
            interval=1000 // fps,
            blit=False,
        )
        writer = FFMpegWriter(
            fps=fps, bitrate=2000,
            metadata={"title": "H2O DeePMD-kit MD"},
        )
        ani.save(output, writer=writer, dpi=130)
        print(f"Saved: {output}")
        plt.close(self.fig)


# ===========================================================================
if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Render DeePMD-kit MD animation from deepmd_data.npz"
    )
    parser.add_argument("--data",   default=NPZ_PATH,
                        help="Path to deepmd_data.npz")
    parser.add_argument("--output", default="part2c_deepmd.mp4",
                        help="Output mp4 filename")
    parser.add_argument("--fps",    type=int, default=FPS_C,
                        help="Frames per second")
    args = parser.parse_args()

    traj, label = load_data(args.data)
    anim = DeePMDAnimation(traj, model_label=label)
    anim.run(output=args.output, fps=args.fps)
