"""
render_2b_classical.py — Classical FF MD animation for H₂O
===========================================================
Loads pre-computed trajectory from classical_data.npz (generated by
compute_2b_classical.py) and renders the animation.
Compute and render are fully decoupled:

    python part2/compute_2b_classical.py   # ~1 s  — compute once
    python part2/render_2b_classical.py    # ~30 s — render / re-render freely

Layout (2 rows × 3 cols):
  top-left    → Velocity Verlet flowchart (step highlighted)
  bottom-left → 3D molecule (perspective view, elev=25°, azim=45°)
  top-mid     → V_bond parabola with current r indicator
  top-right   → V_angle parabola with current θ indicator
  bottom-mid  → Force decomposition (bond + angle + total arrows)
  bottom-right→ Energy (KE / PE / Total) vs. time

Output: part2b_classical_md.mp4
"""

import os
import sys
sys.path.insert(0, os.path.dirname(__file__))

import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.patches as mpatches
from matplotlib.animation import FuncAnimation, FFMpegWriter
from mpl_toolkits.mplot3d import Axes3D          # noqa: F401
import warnings
warnings.filterwarnings("ignore")

# ---------------------------------------------------------------------------
# Global typography — Arial for all text, Consolas only for the status bar
# ---------------------------------------------------------------------------
matplotlib.rcParams.update({
    "font.family":       "Arial",
    "axes.titlesize":    12,
    "axes.labelsize":    11,
    "xtick.labelsize":   10,
    "ytick.labelsize":   10,
    "legend.fontsize":   9,
})

# ══════════════════════════════════════════════════════════════════════════════
# Force Field Parameters (must match compute_2b_classical.py)
# ══════════════════════════════════════════════════════════════════════════════
K_BOND      = 4.5
R0_OH       = 1.012
K_ANGLE     = 0.33
THETA0      = np.radians(113.24)

ATOM_SYMBOLS = ["O", "H", "H"]
ATOM_COLORS  = ["#E53935", "#1565C0", "#1565C0"]
ATOM_SIZES   = [220, 100, 100]

# ── Timing parameters ─────────────────────────────────────────────────────────
FPS_B          = 6     # output fps for part2b
N_SLOW_LOOPS_B = 2     # first 2 MD steps get pause at key sub-frames
PAUSE_SEC_B    = 1.0   # seconds to pause at each key sub-frame state
KEY_SUBS_B     = {1, 2, 3}

# ── Velocity Verlet flowchart nodes ──────────────────────────────────────────
VV_NODES = [
    ("Initialize",              "#607D8B"),   # 0
    ("Compute\nForces",         "#E53935"),   # 1
    ("Update Velocities\n½-kick", "#2E7D32"), # 2
    ("Update\nPositions",       "#1565C0"),   # 3
    ("Update Velocities\n½-kick", "#2E7D32"), # 4
]
FRAMES_PER_STEP = 4

NPZ_PATH = os.path.join(os.path.dirname(__file__), "classical_data.npz")


# ══════════════════════════════════════════════════════════════════════════════
# Data loader
# ══════════════════════════════════════════════════════════════════════════════

def load_data(path=NPZ_PATH):
    """Load classical_data.npz saved by compute_2b_classical.py."""
    if not os.path.exists(path):
        raise FileNotFoundError(
            f"{path} not found.\n"
            "Run:  python part2/compute_2b_classical.py"
        )
    z = np.load(path)
    n = len(z["step"])
    traj = []
    for i in range(n):
        traj.append({
            "step":       int(z["step"][i]),
            "time_fs":    float(z["time_fs"][i]),
            "positions":  z["positions"][i],
            "velocities": z["velocities"][i],
            "forces":     z["forces"][i],
            "f_bond":     z["f_bond"][i],
            "f_angle":    z["f_angle"][i],
            "r1":         float(z["r1"][i]),
            "r2":         float(z["r2"][i]),
            "theta_deg":  float(z["theta_deg"][i]),
            "V_bond":     float(z["V_bond"][i]),
            "V_angle":    float(z["V_angle"][i]),
            "V_total":    float(z["V_total"][i]),
            "KE":         float(z["KE"][i]),
            "TE":         float(z["TE"][i]),
        })
    print(f"Loaded {n} MD steps from {path}")
    return traj


# ══════════════════════════════════════════════════════════════════════════════
# Animation
# ══════════════════════════════════════════════════════════════════════════════

class ClassicalMDAnimation:
    def __init__(self, traj):
        self.traj = traj
        n_md = len(self.traj)

        # ── Build frame schedule with pauses on first N_SLOW_LOOPS_B steps ──────
        pause_frames = max(1, int(round(FPS_B * PAUSE_SEC_B)))
        schedule = []
        for step in range(n_md):
            for sub in range(FRAMES_PER_STEP):
                reps = pause_frames if (step < N_SLOW_LOOPS_B and sub in KEY_SUBS_B) else 1
                schedule.extend([(step, sub)] * reps)
        self.frame_schedule = schedule
        self.n_frames = len(schedule)

        # ── Figure ─────────────────────────────────────────────────────────────
        self.fig = plt.figure(figsize=(16, 9), facecolor="white")
        self.fig.patch.set_facecolor("white")

        gs = gridspec.GridSpec(
            2, 3, figure=self.fig,
            width_ratios=[1.1, 1.3, 1.3],
            hspace=0.50, wspace=0.40,
            left=0.05, right=0.97, top=0.93, bottom=0.07
        )

        # Left column
        self.ax_flow = self.fig.add_subplot(gs[0, 0])
        self.ax_mol  = self.fig.add_subplot(gs[1, 0], projection="3d")

        # Right panels
        self.ax_vbond  = self.fig.add_subplot(gs[0, 1])
        self.ax_vangle = self.fig.add_subplot(gs[0, 2])
        self.ax_force  = self.fig.add_subplot(gs[1, 1])
        self.ax_energy = self.fig.add_subplot(gs[1, 2])

        for ax in [self.ax_flow, self.ax_vbond, self.ax_vangle,
                   self.ax_force, self.ax_energy]:
            ax.set_facecolor("white")

        # Fixed-width Consolas status bar — no suptitle
        self._status_txt = self.fig.text(
            0.5, 0.965, "",
            ha="center", va="top",
            fontsize=12, color="#333333",
            fontfamily="Consolas",
        )

        # Pre-compute potential curves
        self.r_range     = np.linspace(0.6, 1.6, 200)
        self.V_bond_curve = 0.5 * K_BOND * (self.r_range - R0_OH)**2
        self.theta_range  = np.linspace(np.radians(60), np.radians(160), 200)
        self.V_angle_curve = 0.5 * K_ANGLE * (self.theta_range - THETA0)**2

        # Pre-extract time series
        self.times  = [d["time_fs"] for d in self.traj]
        self.KE_arr = [d["KE"] for d in self.traj]
        self.PE_arr = [d["V_total"] for d in self.traj]
        self.TE_arr = [d["TE"] for d in self.traj]

    # ── Flowchart ─────────────────────────────────────────────────────────────
    def _draw_flowchart(self, ax, active_node):
        ax.cla()
        ax.set_facecolor("white")
        ax.set_xlim(0, 1)
        ax.set_ylim(0, 1)
        ax.axis("off")
        ax.set_title("Velocity Verlet", fontsize=11,
                     color="#1565C0", fontweight="bold", pad=3)

        n = len(VV_NODES)
        ys = np.linspace(0.93, 0.05, n)
        x_center = 0.50
        box_w, box_h = 0.80, 0.085

        for i, (label, base_col) in enumerate(VV_NODES):
            y = ys[i]
            is_active = (i == active_node)
            face  = "#FFEB3B" if is_active else base_col
            edge  = "#F57F17" if is_active else base_col
            lw    = 2.5 if is_active else 1.0
            alpha = 1.0 if is_active else 0.18

            rect = mpatches.FancyBboxPatch(
                (x_center - box_w / 2, y - box_h / 2),
                box_w, box_h,
                boxstyle="round,pad=0.01",
                facecolor=face if is_active else base_col,
                edgecolor=edge,
                linewidth=lw,
                alpha=alpha,
                transform=ax.transAxes, clip_on=False
            )
            ax.add_patch(rect)

            txt_col   = "#1A1A1A" if is_active else "white"
            txt_alpha = 1.0 if is_active else 0.85
            ax.text(x_center, y, label,
                    ha="center", va="center",
                    fontsize=9, color=txt_col,
                    fontweight="bold" if is_active else "normal",
                    alpha=txt_alpha,
                    transform=ax.transAxes)

            if i < n - 1:
                ax.annotate(
                    "", xy=(x_center, ys[i + 1] + box_h / 2 + 0.005),
                    xytext=(x_center, y - box_h / 2 - 0.005),
                    xycoords="axes fraction", textcoords="axes fraction",
                    arrowprops=dict(arrowstyle="-|>", color="#888888",
                                   lw=1.0, mutation_scale=8)
                )

        # Loop-back arrow
        ax.annotate(
            "", xy=(x_center - box_w / 2 - 0.02, ys[1]),
            xytext=(x_center - box_w / 2 - 0.02, ys[-1]),
            xycoords="axes fraction", textcoords="axes fraction",
            arrowprops=dict(arrowstyle="-|>", color="#888888",
                            lw=1.0, mutation_scale=8)
        )
        ax.text(0.02, (ys[1] + ys[-1]) / 2, "loop",
                ha="center", va="center", fontsize=9,
                color="#888888", rotation=90,
                transform=ax.transAxes)

    # ── 3D molecule ───────────────────────────────────────────────────────────
    def _draw_molecule_3d(self, ax, d, show_forces=False,
                          show_vel=False, show_disp=False):
        ax.cla()
        ax.set_facecolor("white")
        ax.view_init(elev=25, azim=45)

        pos = d["positions"]
        r1, r2 = d["r1"], d["r2"]
        theta_deg = d["theta_deg"]

        # Bonds
        for i in range(1, 3):
            ax.plot(
                [pos[0, 0], pos[i, 0]],
                [pos[0, 1], pos[i, 1]],
                [pos[0, 2], pos[i, 2]],
                color="#888888", linewidth=2.5, zorder=1
            )

        # Atoms
        for i, (sym, col, sz) in enumerate(zip(ATOM_SYMBOLS, ATOM_COLORS, ATOM_SIZES)):
            ax.scatter(pos[i, 0], pos[i, 1], pos[i, 2],
                       s=sz, c=col, edgecolors="white",
                       linewidths=1.5, zorder=5, depthshade=True)
            ax.text(pos[i, 0] + 0.06, pos[i, 1] + 0.06, pos[i, 2] + 0.10,
                    sym, fontsize=11, color=col, fontweight="bold")

        # Force arrows — only during "compute forces" sub-frame
        if show_forces:
            forces = d["forces"]
            f_max = np.abs(forces).max() + 1e-10
            scale = 0.35 / f_max
            for i in range(3):
                f = forces[i] * scale
                if np.linalg.norm(f) > 0.01:
                    ax.quiver(pos[i, 0], pos[i, 1], pos[i, 2],
                              f[0], f[1], f[2],
                              color="#E65100", arrow_length_ratio=0.35,
                              linewidth=1.5, zorder=10)

        # Velocity arrows — only during "vel ½-kick" sub-frame
        if show_vel:
            vel = d["velocities"]
            v_max = np.abs(vel).max() + 1e-10
            scale = 0.35 / v_max
            for i in range(3):
                v = vel[i] * scale
                if np.linalg.norm(v) > 0.01:
                    ax.quiver(pos[i, 0], pos[i, 1], pos[i, 2],
                              v[0], v[1], v[2],
                              color="#2E7D32", arrow_length_ratio=0.35,
                              linewidth=1.5, zorder=10)

        # Displacement arrows — only during "pos update" sub-frame
        if show_disp:
            eq_pos = np.array([
                [0.0, 0.0, 0.0],
                [ R0_OH * np.sin(THETA0/2), 0.0, R0_OH * np.cos(THETA0/2)],
                [-R0_OH * np.sin(THETA0/2), 0.0, R0_OH * np.cos(THETA0/2)],
            ])
            disp = pos - eq_pos
            d_max = np.abs(disp).max() + 1e-10
            scale = 0.35 / d_max
            for i in range(3):
                dv = disp[i] * scale
                if np.linalg.norm(dv) > 0.005:
                    ax.quiver(eq_pos[i, 0], eq_pos[i, 1], eq_pos[i, 2],
                              dv[0], dv[1], dv[2],
                              color="#1565C0", arrow_length_ratio=0.35,
                              linewidth=1.5, zorder=10)

        # Geometry labels
        ax.text2D(0.02, 0.95, f"r₁={r1:.3f} Å", transform=ax.transAxes,
                  fontsize=10, color="#1565C0")
        ax.text2D(0.02, 0.88, f"r₂={r2:.3f} Å", transform=ax.transAxes,
                  fontsize=10, color="#1565C0")
        ax.text2D(0.02, 0.81, f"θ={theta_deg:.1f}°", transform=ax.transAxes,
                  fontsize=10, color="#E65100")

        ax.set_xlim(-1.2, 1.2)
        ax.set_ylim(-1.2, 1.2)
        ax.set_zlim(-1.2, 1.2)
        ax.set_xlabel("x (Å)", fontsize=10, labelpad=1)
        ax.set_ylabel("y (Å)", fontsize=10, labelpad=1)
        ax.set_zlabel("z (Å)", fontsize=10, labelpad=1)
        ax.tick_params(labelsize=9)
        ax.xaxis.pane.fill = False
        ax.yaxis.pane.fill = False
        ax.zaxis.pane.fill = False
        ax.grid(True, alpha=0.15)
        ax.set_title(f"H₂O  (t = {d['time_fs']:.1f} fs)", fontsize=11,
                     color="#1565C0", pad=2)

    # ── V_bond curve ──────────────────────────────────────────────────────────
    def _draw_vbond(self, ax, r1, r2):
        ax.cla()
        ax.set_facecolor("white")
        ax.plot(self.r_range, self.V_bond_curve, color="#1565C0", linewidth=2)
        ax.axvline(R0_OH, color="#1B5E20", linestyle="--", linewidth=1,
                   alpha=0.7, label=f"r₀={R0_OH} Å")
        V1 = 0.5 * K_BOND * (r1 - R0_OH)**2
        V2 = 0.5 * K_BOND * (r2 - R0_OH)**2
        ax.scatter([r1, r2], [V1, V2], s=80,
                   c=["#E53935", "#E65100"], zorder=5, label="r₁, r₂")
        ax.set_xlabel("r (Å)", fontsize=11)
        ax.set_ylabel("V_bond (eV)", fontsize=11)
        ax.set_title(r"$V_{\rm bond}=\frac{1}{2}k(r-r_0)^2$",
                     fontsize=12, color="#1565C0")
        ax.set_xlim(0.6, 1.6)
        ax.legend(fontsize=10)
        ax.tick_params(labelsize=10)
        ax.grid(True, alpha=0.3)

    # ── V_angle curve ─────────────────────────────────────────────────────────
    def _draw_vangle(self, ax, theta_deg):
        ax.cla()
        ax.set_facecolor("white")
        theta_deg_range = np.degrees(self.theta_range)
        ax.plot(theta_deg_range, self.V_angle_curve, color="#E65100", linewidth=2)
        ax.axvline(np.degrees(THETA0), color="#1B5E20", linestyle="--",
                   linewidth=1, alpha=0.7, label=f"θ₀={np.degrees(THETA0):.1f}°")
        theta_rad = np.radians(theta_deg)
        Va = 0.5 * K_ANGLE * (theta_rad - THETA0)**2
        ax.scatter([theta_deg], [Va], s=80, c="#E53935", zorder=5, label="current θ")
        ax.set_xlabel("θ (°)", fontsize=11)
        ax.set_ylabel("V_angle (eV)", fontsize=11)
        ax.set_title(r"$V_{\rm angle}=\frac{1}{2}k_\theta(\theta-\theta_0)^2$",
                     fontsize=12, color="#E65100")
        ax.legend(fontsize=10)
        ax.tick_params(labelsize=10)
        ax.grid(True, alpha=0.3)

    # ── Force decomposition (2D xz projection) ────────────────────────────────
    def _draw_forces(self, ax, d):
        ax.cla()
        ax.set_facecolor("white")
        pos    = d["positions"]
        forces = d["forces"]
        f_bond = d["f_bond"]
        f_angle= d["f_angle"]
        xs, zs = pos[:, 0], pos[:, 2]

        # Bonds
        for i in range(1, 3):
            ax.plot([xs[0], xs[i]], [zs[0], zs[i]],
                    color="#CCCCCC", linewidth=3, zorder=1)

        # Atoms
        for i, (sym, col, sz) in enumerate(zip(ATOM_SYMBOLS, ATOM_COLORS, ATOM_SIZES)):
            ax.scatter(xs[i], zs[i], s=sz, c=col,
                       edgecolors="white", linewidths=2, zorder=5)
            ax.text(xs[i] + 0.04, zs[i] + 0.06, sym,
                    fontsize=11, color=col, fontweight="bold", zorder=6)

        f_max = max(np.abs(forces).max(), 1e-6)
        scale = 0.45 / f_max

        arrow_styles = [
            (forces,  "#333333", "Total",  2.5),
            (f_bond,  "#1565C0", "Bond",   1.5),
            (f_angle, "#E65100", "Angle",  1.5),
        ]
        for f_arr, col, lbl, lw in arrow_styles:
            for i in range(3):
                fx = f_arr[i, 0] * scale
                fz = f_arr[i, 2] * scale
                if abs(fx) + abs(fz) > 0.005:
                    ax.annotate(
                        "", xy=(xs[i] + fx, zs[i] + fz),
                        xytext=(xs[i], zs[i]),
                        arrowprops=dict(arrowstyle="->", color=col,
                                        lw=lw, mutation_scale=12)
                    )

        legend_patches = [
            mpatches.Patch(facecolor="#333333", label="Total"),
            mpatches.Patch(facecolor="#1565C0", label="Bond"),
            mpatches.Patch(facecolor="#E65100", label="Angle"),
        ]
        ax.legend(handles=legend_patches, fontsize=10, loc="upper right")

        ax.set_xlim(-1.5, 1.5)
        ax.set_ylim(-0.5, 1.8)
        ax.set_xlabel("x (Å)", fontsize=11)
        ax.set_ylabel("z (Å)", fontsize=11)
        ax.set_title("Force Decomposition (Bond + Angle)", fontsize=12, color="#1565C0")
        ax.set_aspect("equal")
        ax.tick_params(labelsize=7)
        ax.grid(True, alpha=0.2)

        for i, sym in enumerate(ATOM_SYMBOLS):
            fmag = np.linalg.norm(forces[i])
            ax.text(0.02, 0.95 - i * 0.11,
                    f"|F_{sym}| = {fmag:.3f} eV/Å",
                    transform=ax.transAxes, fontsize=10,
                    color=ATOM_COLORS[i])

    # ── Energy ────────────────────────────────────────────────────────────────
    def _draw_energy(self, ax, frame_idx):
        ax.cla()
        ax.set_facecolor("white")
        t = self.times[:frame_idx + 1]
        ax.plot(t, self.KE_arr[:frame_idx + 1], "-", color="#E65100",
                linewidth=2, label="KE")
        ax.plot(t, self.PE_arr[:frame_idx + 1], "-", color="#1565C0",
                linewidth=2, label="PE")
        ax.plot(t, self.TE_arr[:frame_idx + 1], "-", color="#1B5E20",
                linewidth=2.5, label="Total E")
        ax.set_xlabel("Time (fs)", fontsize=11)
        ax.set_ylabel("Energy (eV)", fontsize=11)
        ax.set_title("Energy Conservation", fontsize=12, color="#1565C0")
        ax.set_xlim(-0.5, self.times[-1] + 0.5)
        ax.legend(fontsize=10, loc="upper right")
        ax.tick_params(labelsize=10)
        ax.grid(True, alpha=0.3)

        if frame_idx > 5:
            te_std  = np.std(self.TE_arr[:frame_idx + 1])
            te_mean = np.mean(self.TE_arr[:frame_idx + 1])
            ax.text(0.02, 0.05,
                    f"ΔE/E = {te_std / (abs(te_mean) + 1e-12) * 100:.3f}%",
                    transform=ax.transAxes, fontsize=10, color="#555555")

    # ── Main animate ──────────────────────────────────────────────────────────
    def animate(self, frame_idx):
        step_idx, sub = self.frame_schedule[frame_idx]
        d = self.traj[step_idx]

        # Active flowchart node
        if step_idx == 0 and sub == 0:
            active_node = 0   # Initialize
        elif sub <= 1:
            active_node = 1   # Compute Forces
        elif sub == 2:
            active_node = 2   # Update Velocities ½-kick
        else:
            active_node = 3   # Update Positions

        show_forces = (sub == 1)
        show_vel    = (sub == 2)
        show_disp   = (sub == 3)

        self._draw_flowchart(self.ax_flow, active_node)
        self._draw_molecule_3d(self.ax_mol, d,
                               show_forces=show_forces,
                               show_vel=show_vel,
                               show_disp=show_disp)
        self._draw_vbond(self.ax_vbond, d["r1"], d["r2"])
        self._draw_vangle(self.ax_vangle, d["theta_deg"])
        self._draw_forces(self.ax_force, d)
        self._draw_energy(self.ax_energy, step_idx)

        phases = {
            0: "Initializing          ",
            1: "Computing forces      ",
            2: "Velocity half-kick    ",
            3: "Updating positions    ",
        }
        phase_str = phases.get(active_node, "                      ")
        n_steps = len(self.traj)
        status = (f"Step {step_idx+1:02d}/{n_steps:02d}"
                  f"  |  t = {d['time_fs']:5.1f} fs"
                  f"  |  {phase_str}")
        self._status_txt.set_text(status)
        return []

    def run(self, output="part2b_classical_md.mp4", fps=FPS_B):
        print(f"\nRendering {self.n_frames} frames @ {fps} fps → {output}")
        print(f"  Duration: {self.n_frames / fps:.1f}s")
        ani = FuncAnimation(self.fig, self.animate,
                            frames=self.n_frames,
                            interval=1000 // fps, blit=False)
        writer = FFMpegWriter(fps=fps, bitrate=2500,
                              metadata={"title": "Classical FF MD H2O"})
        ani.save(output, writer=writer, dpi=130)
        print(f"Saved: {output}")
        plt.close(self.fig)


# ══════════════════════════════════════════════════════════════════════════════
if __name__ == "__main__":
    traj = load_data()
    anim = ClassicalMDAnimation(traj)
    anim.run(output="part2b_classical_md.mp4")
